"""Exact ecosystem simulation with institutional conservation checks."""

from bridgman import Dimensions, canonicalize_dims

from ecosim._core import (
    BalanceReport,
    DenseFoodWeb,
    DenseFoodWebStep,
    FoodWeb,
    FoodWebParameters,
    FoodWebStep,
    World,
    energy_law_coefficients,
    simulate_food_web,
)
from ecosim.experiments import (
    BoundaryPerturbation,
    FoodWebResponse,
    simulate_food_web_response,
)
from ecosim.cascade import (
    CascadeExperimentResult,
    ExactSignClaim,
    ExactSignObservation,
    FrozenCascadeScenario,
    ResponseClaim,
    ResponseObservation,
    load_frozen_cascade,
    run_frozen_cascade,
)
from ecosim.network import (
    Consumer,
    DenseTrophicNetwork,
    DenseTrophicNetworkPlan,
    DenseTrophicNetworkStep,
    Feeding,
    ExactFlowEvidence,
    ExactPairedSentenceEvidence,
    ExactTransitionEvidence,
    Producer,
    TrophicNetwork,
    TrophicNetworkPlan,
    TrophicNetworkSpec,
    TrophicNetworkStep,
    TrophicEvidence,
    TrophicLaw,
    TrophicLawEvidence,
)
from ecosim.trophic_experiments import (
    ExactTrophicAudit,
    ExactTrophicComparison,
    TrophicIntervention,
    TrophicResponse,
    TrophicTrajectory,
    audit_exact_trophic_run,
    simulate_trophic_response,
    simulate_trophic_trajectory,
)

ENERGY_DIMENSIONS: Dimensions = canonicalize_dims({"M": 1, "L": 2, "T": -2})

__all__ = [
    "BalanceReport",
    "BoundaryPerturbation",
    "CascadeExperimentResult",
    "Consumer",
    "DenseFoodWeb",
    "DenseFoodWebStep",
    "DenseTrophicNetwork",
    "DenseTrophicNetworkPlan",
    "DenseTrophicNetworkStep",
    "ENERGY_DIMENSIONS",
    "ExactSignClaim",
    "ExactSignObservation",
    "ExactFlowEvidence",
    "ExactPairedSentenceEvidence",
    "ExactTransitionEvidence",
    "ExactTrophicAudit",
    "ExactTrophicComparison",
    "FoodWeb",
    "FoodWebParameters",
    "FoodWebResponse",
    "FrozenCascadeScenario",
    "Feeding",
    "Producer",
    "ResponseClaim",
    "ResponseObservation",
    "TrophicNetwork",
    "TrophicNetworkPlan",
    "TrophicNetworkSpec",
    "TrophicNetworkStep",
    "TrophicEvidence",
    "TrophicLaw",
    "TrophicLawEvidence",
    "TrophicIntervention",
    "TrophicResponse",
    "TrophicTrajectory",
    "FoodWebStep",
    "World",
    "energy_law_coefficients",
    "audit_exact_trophic_run",
    "load_frozen_cascade",
    "run_frozen_cascade",
    "simulate_food_web",
    "simulate_food_web_response",
    "simulate_trophic_response",
    "simulate_trophic_trajectory",
]
