class BalanceReport:
    @property
    def initial_stock(self) -> int: ...
    @property
    def inputs(self) -> int: ...
    @property
    def outputs(self) -> int: ...
    @property
    def final_stock(self) -> int: ...
    @property
    def residual(self) -> int: ...
    @property
    def balanced(self) -> bool: ...

class World:
    def __init__(self, left: int, right: int) -> None: ...
    @property
    def left(self) -> int: ...
    @property
    def right(self) -> int: ...
    @property
    def net_external(self) -> int: ...
    @property
    def history_length(self) -> int: ...
    def transfer(self, source: str, target: str, amount: int) -> None: ...
    def input(self, target: str, amount: int) -> None: ...
    def output(self, source: str, amount: int) -> None: ...
    def report(self) -> BalanceReport: ...
    def conserves_total_energy(self) -> bool: ...

def energy_law_coefficients() -> dict[str, int]: ...
