import numpy as np
from numpy.typing import NDArray

class BalanceReport:
    @property
    def initial_stock(self) -> int: ...
    @property
    def inputs(self) -> int: ...
    @property
    def outputs(self) -> int: ...
    @property
    def final_stock(self) -> int: ...
    @property
    def residual(self) -> int: ...
    @property
    def balanced(self) -> bool: ...

class World:
    def __init__(self, left: int, right: int) -> None: ...
    @property
    def left(self) -> int: ...
    @property
    def right(self) -> int: ...
    @property
    def net_external(self) -> int: ...
    @property
    def history_length(self) -> int: ...
    def transfer(self, source: str, target: str, amount: int) -> None: ...
    def input(self, target: str, amount: int) -> None: ...
    def output(self, source: str, amount: int) -> None: ...
    def report(self) -> BalanceReport: ...
    def conserves_total_energy(self) -> bool: ...

class FoodWebStep:
    @property
    def elapsed(self) -> float: ...
    def applied(self, process: str) -> float: ...

class FoodWeb:
    def __init__(self, nutrient: float, producer: float, consumer: float, detritus: float) -> None: ...
    @property
    def time(self) -> float: ...
    @property
    def nutrient(self) -> float: ...
    @property
    def producer(self) -> float: ...
    @property
    def consumer(self) -> float: ...
    @property
    def detritus(self) -> float: ...
    @property
    def inputs(self) -> float: ...
    @property
    def outputs(self) -> float: ...
    @property
    def balance_residual(self) -> float: ...
    @property
    def balanced(self) -> bool: ...
    def step(
        self,
        elapsed: float,
        nutrient_input: float = 0.0,
        harvest: float = 0.0,
    ) -> FoodWebStep: ...

class DenseFoodWebStep:
    @property
    def elapsed(self) -> float: ...
    def applied(self, process: str) -> float: ...

class DenseFoodWeb:
    def __init__(self, nutrient: float, producer: float, consumer: float, detritus: float) -> None: ...
    @property
    def time(self) -> float: ...
    @property
    def nutrient(self) -> float: ...
    @property
    def producer(self) -> float: ...
    @property
    def consumer(self) -> float: ...
    @property
    def detritus(self) -> float: ...
    @property
    def inputs(self) -> float: ...
    @property
    def outputs(self) -> float: ...
    @property
    def balance_residual(self) -> float: ...
    @property
    def balanced(self) -> bool: ...
    def step(
        self,
        elapsed: float,
        nutrient_input: float = 0.0,
        harvest: float = 0.0,
    ) -> DenseFoodWebStep: ...

def simulate_food_web(
    initial_states: NDArray[np.float64],
    steps: int,
    elapsed: float,
    nutrient_inputs: NDArray[np.float64] | None = None,
    harvests: NDArray[np.float64] | None = None,
) -> NDArray[np.float64]: ...

def energy_law_coefficients() -> dict[str, int]: ...
