import numpy as np
from numpy.typing import NDArray

class BalanceReport:
    @property
    def initial_stock(self) -> int: ...
    @property
    def inputs(self) -> int: ...
    @property
    def outputs(self) -> int: ...
    @property
    def final_stock(self) -> int: ...
    @property
    def residual(self) -> int: ...
    @property
    def balanced(self) -> bool: ...

class World:
    def __init__(self, left: int, right: int) -> None: ...
    @property
    def left(self) -> int: ...
    @property
    def right(self) -> int: ...
    @property
    def net_external(self) -> int: ...
    @property
    def history_length(self) -> int: ...
    def transfer(self, source: str, target: str, amount: int) -> None: ...
    def input(self, target: str, amount: int) -> None: ...
    def output(self, source: str, amount: int) -> None: ...
    def report(self) -> BalanceReport: ...
    def conserves_total_energy(self) -> bool: ...

class FoodWebStep:
    @property
    def elapsed(self) -> float: ...
    def applied(self, process: str) -> float: ...

class FoodWebParameters:
    def __init__(
        self,
        max_growth: float = 0.5,
        nutrient_half_saturation: float = 10.0,
        max_grazing: float = 0.4,
        producer_half_saturation: float = 10.0,
        producer_mortality: float = 0.05,
        consumer_mortality: float = 0.04,
        decomposition: float = 0.1,
    ) -> None: ...
    @property
    def max_growth(self) -> float: ...
    @property
    def nutrient_half_saturation(self) -> float: ...
    @property
    def max_grazing(self) -> float: ...
    @property
    def producer_half_saturation(self) -> float: ...
    @property
    def producer_mortality(self) -> float: ...
    @property
    def consumer_mortality(self) -> float: ...
    @property
    def decomposition(self) -> float: ...

class FoodWeb:
    def __init__(
        self,
        nutrient: float,
        producer: float,
        consumer: float,
        detritus: float,
        parameters: FoodWebParameters | None = None,
    ) -> None: ...
    @property
    def time(self) -> float: ...
    @property
    def nutrient(self) -> float: ...
    @property
    def producer(self) -> float: ...
    @property
    def consumer(self) -> float: ...
    @property
    def detritus(self) -> float: ...
    @property
    def inputs(self) -> float: ...
    @property
    def outputs(self) -> float: ...
    @property
    def balance_residual(self) -> float: ...
    @property
    def balanced(self) -> bool: ...
    def step(
        self,
        elapsed: float,
        nutrient_input: float = 0.0,
        harvest: float = 0.0,
    ) -> FoodWebStep: ...

class DenseFoodWebStep:
    @property
    def elapsed(self) -> float: ...
    def applied(self, process: str) -> float: ...

class DenseFoodWeb:
    def __init__(
        self,
        nutrient: float,
        producer: float,
        consumer: float,
        detritus: float,
        parameters: FoodWebParameters | None = None,
    ) -> None: ...
    @property
    def time(self) -> float: ...
    @property
    def nutrient(self) -> float: ...
    @property
    def producer(self) -> float: ...
    @property
    def consumer(self) -> float: ...
    @property
    def detritus(self) -> float: ...
    @property
    def inputs(self) -> float: ...
    @property
    def outputs(self) -> float: ...
    @property
    def balance_residual(self) -> float: ...
    @property
    def balanced(self) -> bool: ...
    def step(
        self,
        elapsed: float,
        nutrient_input: float = 0.0,
        harvest: float = 0.0,
    ) -> DenseFoodWebStep: ...

class TrophicNetworkStep:
    @property
    def elapsed(self) -> float: ...
    def growth(self, producer: str) -> float | None: ...
    def feeding(self, consumer: str, resource: str) -> float | None: ...
    def mortality(self, stock: str) -> float | None: ...
    def harvest(self, consumer: str) -> float | None: ...
    def decomposition(self) -> float: ...

class NativeTrophicNetworkPlan:
    def __init__(
        self,
        producers: list[tuple[str, float, float, float]],
        consumers: list[tuple[str, float]],
        feedings: list[tuple[str, str, float, float, float]],
        decomposition: float,
    ) -> None: ...
    @property
    def stock_names(self) -> list[str]: ...
    @property
    def consumer_names(self) -> list[str]: ...
    def start(self, initial: dict[str, float]) -> NativeTrophicNetwork: ...

class NativeTrophicNetwork:
    def __init__(
        self,
        producers: list[tuple[str, float, float, float]],
        consumers: list[tuple[str, float]],
        feedings: list[tuple[str, str, float, float, float]],
        decomposition: float,
        initial: dict[str, float],
    ) -> None: ...
    @property
    def time(self) -> float: ...
    @property
    def stock_names(self) -> list[str]: ...
    def stock(self, name: str) -> float: ...
    @property
    def inputs(self) -> float: ...
    @property
    def outputs(self) -> float: ...
    @property
    def balance_residual(self) -> float: ...
    @property
    def balanced(self) -> bool: ...
    def step(
        self,
        elapsed: float,
        nutrient_input: float = 0.0,
        harvests: dict[str, float] | None = None,
    ) -> TrophicNetworkStep: ...

class DenseTrophicNetworkStep:
    @property
    def elapsed(self) -> float: ...
    def growth(self, producer: str) -> float | None: ...
    def feeding(self, consumer: str, resource: str) -> float | None: ...
    def mortality(self, stock: str) -> float | None: ...
    def harvest(self, consumer: str) -> float | None: ...
    def decomposition(self) -> float: ...

class NativeDenseTrophicNetworkPlan:
    def __init__(
        self,
        producers: list[tuple[str, float, float, float]],
        consumers: list[tuple[str, float]],
        feedings: list[tuple[str, str, float, float, float]],
        decomposition: float,
    ) -> None: ...
    @property
    def stock_names(self) -> list[str]: ...
    @property
    def consumer_names(self) -> list[str]: ...
    def start(self, initial: dict[str, float]) -> NativeDenseTrophicNetwork: ...
    def simulate(
        self,
        initial_states: NDArray[np.float64],
        steps: int,
        elapsed: float,
        nutrient_inputs: NDArray[np.float64] | None = None,
        harvests: NDArray[np.float64] | None = None,
    ) -> NDArray[np.float64]: ...

class NativeDenseTrophicNetwork:
    def __init__(
        self,
        producers: list[tuple[str, float, float, float]],
        consumers: list[tuple[str, float]],
        feedings: list[tuple[str, str, float, float, float]],
        decomposition: float,
        initial: dict[str, float],
    ) -> None: ...
    @property
    def time(self) -> float: ...
    @property
    def stock_names(self) -> list[str]: ...
    def stock(self, name: str) -> float: ...
    @property
    def inputs(self) -> float: ...
    @property
    def outputs(self) -> float: ...
    @property
    def balance_residual(self) -> float: ...
    @property
    def balanced(self) -> bool: ...
    def step(
        self,
        elapsed: float,
        nutrient_input: float = 0.0,
        harvests: dict[str, float] | None = None,
    ) -> DenseTrophicNetworkStep: ...

def simulate_food_web(
    initial_states: NDArray[np.float64],
    steps: int,
    elapsed: float,
    nutrient_inputs: NDArray[np.float64] | None = None,
    harvests: NDArray[np.float64] | None = None,
    parameters: FoodWebParameters | None = None,
) -> NDArray[np.float64]: ...

def energy_law_coefficients() -> dict[str, int]: ...
